<?php

function setup_schema_statements(): array
{
    return [
        "SET NAMES utf8mb4",
        "SET time_zone = '+07:00'",
        "CREATE TABLE IF NOT EXISTS users (
            id INT AUTO_INCREMENT PRIMARY KEY,
            username VARCHAR(60) NOT NULL UNIQUE,
            full_name VARCHAR(120) NOT NULL,
            role ENUM('kasir','manajer','adminsuper') NOT NULL DEFAULT 'kasir',
            password_hash VARCHAR(255) NOT NULL,
            is_active TINYINT(1) NOT NULL DEFAULT 1,
            last_login_at DATETIME NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            created_by INT NULL,
            INDEX idx_role (role),
            INDEX idx_active (is_active)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS auth_tokens (
            id INT AUTO_INCREMENT PRIMARY KEY,
            selector VARCHAR(32) NOT NULL UNIQUE,
            hashed_validator VARCHAR(255) NOT NULL,
            user_id INT NOT NULL,
            expires_at DATETIME NOT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_user (user_id),
            CONSTRAINT fk_auth_tokens_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS categories (
            id INT AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(120) NOT NULL UNIQUE,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS suppliers (
            id INT AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(150) NOT NULL,
            contact_person VARCHAR(120) NULL,
            phone VARCHAR(40) NULL,
            email VARCHAR(120) NULL,
            address TEXT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS products (
            id INT AUTO_INCREMENT PRIMARY KEY,
            barcode VARCHAR(64) NULL,
            name VARCHAR(180) NOT NULL,
            category_id INT NULL,
            unit VARCHAR(40) NULL,
            stock_minimum INT NOT NULL DEFAULT 0,
            description TEXT NULL,
            image_path VARCHAR(255) NULL,
            points_reward INT NOT NULL DEFAULT 0,
            is_active TINYINT(1) NOT NULL DEFAULT 1,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uk_products_barcode (barcode),
            INDEX idx_products_category (category_id),
            CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS product_batches (
            id INT AUTO_INCREMENT PRIMARY KEY,
            product_id INT NOT NULL,
            supplier_id INT NULL,
            source_batch_id INT NULL,
            batch_code VARCHAR(80) NOT NULL,
            stock_in INT NOT NULL DEFAULT 0,
            stock_remaining INT NOT NULL DEFAULT 0,
            purchase_price DECIMAL(12,2) NOT NULL DEFAULT 0,
            sell_price DECIMAL(12,2) NOT NULL DEFAULT 0,
            expiry_date DATE NULL,
            received_at DATETIME NULL,
            label_printed TINYINT(1) NOT NULL DEFAULT 0,
            label_printed_at DATETIME NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            INDEX idx_batches_product (product_id),
            INDEX idx_batches_supplier (supplier_id),
            INDEX idx_batches_expiry (expiry_date),
            CONSTRAINT fk_batches_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
            CONSTRAINT fk_batches_supplier FOREIGN KEY (supplier_id) REFERENCES suppliers(id) ON DELETE SET NULL,
            CONSTRAINT fk_batches_source FOREIGN KEY (source_batch_id) REFERENCES product_batches(id) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS product_conversions (
            id INT AUTO_INCREMENT PRIMARY KEY,
            parent_product_id INT NOT NULL,
            child_product_id INT NOT NULL,
            child_quantity DECIMAL(12,3) NOT NULL DEFAULT 0,
            auto_breakdown TINYINT(1) NOT NULL DEFAULT 0,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uk_conversion_child (child_product_id),
            INDEX idx_conversion_parent (parent_product_id),
            CONSTRAINT fk_conversion_parent FOREIGN KEY (parent_product_id) REFERENCES products(id) ON DELETE CASCADE,
            CONSTRAINT fk_conversion_child FOREIGN KEY (child_product_id) REFERENCES products(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS stock_adjustments (
            id INT AUTO_INCREMENT PRIMARY KEY,
            product_id INT NOT NULL,
            batch_id INT NOT NULL,
            adjustment_type ENUM('initial','purchase','sale','return','adjust','transfer','convert_in','convert_out','expired','in') NOT NULL DEFAULT 'adjust',
            quantity INT NOT NULL DEFAULT 0,
            reason TEXT NULL,
            created_by INT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_stock_product (product_id),
            INDEX idx_stock_batch (batch_id),
            INDEX idx_stock_type (adjustment_type),
            CONSTRAINT fk_stock_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
            CONSTRAINT fk_stock_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id) ON DELETE CASCADE,
            CONSTRAINT fk_stock_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS members (
            id INT AUTO_INCREMENT PRIMARY KEY,
            member_code VARCHAR(50) NOT NULL UNIQUE,
            name VARCHAR(150) NOT NULL,
            phone VARCHAR(40) NULL,
            email VARCHAR(120) NULL,
            address TEXT NULL,
            status ENUM('active','inactive') NOT NULL DEFAULT 'active',
            points_balance INT NOT NULL DEFAULT 0,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS sales (
            id INT AUTO_INCREMENT PRIMARY KEY,
            invoice_code VARCHAR(40) NOT NULL UNIQUE,
            member_id INT NULL,
            cashier_id INT NOT NULL,
            total_items INT NOT NULL DEFAULT 0,
            subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
            discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
            points_used INT NOT NULL DEFAULT 0,
            points_earned INT NOT NULL DEFAULT 0,
            grand_total DECIMAL(12,2) NOT NULL DEFAULT 0,
            payment_method ENUM('cash','debit','qris','hutang') NOT NULL DEFAULT 'cash',
            cash_paid DECIMAL(12,2) NOT NULL DEFAULT 0,
            change_returned DECIMAL(12,2) NOT NULL DEFAULT 0,
            notes TEXT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            INDEX idx_sales_created (created_at),
            INDEX idx_sales_member (member_id),
            INDEX idx_sales_cashier (cashier_id),
            CONSTRAINT fk_sales_member FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE SET NULL,
            CONSTRAINT fk_sales_cashier FOREIGN KEY (cashier_id) REFERENCES users(id) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS sale_items (
            id INT AUTO_INCREMENT PRIMARY KEY,
            sale_id INT NOT NULL,
            product_id INT NOT NULL,
            batch_id INT NOT NULL,
            quantity DECIMAL(12,2) NOT NULL DEFAULT 0,
            price DECIMAL(12,2) NOT NULL DEFAULT 0,
            discount DECIMAL(12,2) NOT NULL DEFAULT 0,
            total DECIMAL(12,2) NOT NULL DEFAULT 0,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_items_sale (sale_id),
            INDEX idx_items_product (product_id),
            CONSTRAINT fk_items_sale FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE,
            CONSTRAINT fk_items_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE,
            CONSTRAINT fk_items_batch FOREIGN KEY (batch_id) REFERENCES product_batches(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS member_points (
            id INT AUTO_INCREMENT PRIMARY KEY,
            member_id INT NOT NULL,
            sale_id INT NULL,
            points_change INT NOT NULL DEFAULT 0,
            description VARCHAR(255) NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_points_member (member_id),
            CONSTRAINT fk_points_member FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE,
            CONSTRAINT fk_points_sale FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS expenses (
            id INT AUTO_INCREMENT PRIMARY KEY,
            expense_date DATE NOT NULL,
            category VARCHAR(120) NOT NULL,
            description TEXT NULL,
            amount DECIMAL(12,2) NOT NULL DEFAULT 0,
            created_by INT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            INDEX idx_expense_date (expense_date),
            INDEX idx_expense_user (created_by),
            CONSTRAINT fk_expenses_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS promotions (
            id INT AUTO_INCREMENT PRIMARY KEY,
            product_id INT NULL,
            promo_name VARCHAR(160) NOT NULL,
            promo_type ENUM('item','category','global') NOT NULL DEFAULT 'item',
            discount_value DECIMAL(12,2) NOT NULL DEFAULT 0,
            start_date DATE NULL,
            end_date DATE NULL,
            min_qty INT NOT NULL DEFAULT 1,
            is_active TINYINT(1) NOT NULL DEFAULT 1,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            INDEX idx_promo_product (product_id),
            CONSTRAINT fk_promo_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS store_settings (
            id INT AUTO_INCREMENT PRIMARY KEY,
            store_name VARCHAR(150) NOT NULL,
            address TEXT NULL,
            phone VARCHAR(40) NULL,
            logo_path VARCHAR(255) NULL,
            notes TEXT NULL,
            updated_at DATETIME NOT NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS member_debts (
            id INT AUTO_INCREMENT PRIMARY KEY,
            sale_id INT NOT NULL,
            member_id INT NOT NULL,
            principal_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
            admin_fee DECIMAL(12,2) NOT NULL DEFAULT 0,
            total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
            paid_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
            status ENUM('open','partial','paid') NOT NULL DEFAULT 'open',
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uk_debt_sale (sale_id),
            INDEX idx_debt_member (member_id),
            CONSTRAINT fk_debt_sale FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE,
            CONSTRAINT fk_debt_member FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS member_debt_payments (
            id INT AUTO_INCREMENT PRIMARY KEY,
            debt_id INT NOT NULL,
            member_id INT NOT NULL,
            sale_id INT NOT NULL,
            amount DECIMAL(12,2) NOT NULL DEFAULT 0,
            note VARCHAR(255) NULL,
            paid_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by INT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_debt_payment (debt_id),
            INDEX idx_debt_member (member_id),
            CONSTRAINT fk_debt_payment_debt FOREIGN KEY (debt_id) REFERENCES member_debts(id) ON DELETE CASCADE,
            CONSTRAINT fk_debt_payment_member FOREIGN KEY (member_id) REFERENCES members(id) ON DELETE CASCADE,
            CONSTRAINT fk_debt_payment_sale FOREIGN KEY (sale_id) REFERENCES sales(id) ON DELETE CASCADE,
            CONSTRAINT fk_debt_payment_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS cash_drawer_sessions (
            id INT AUTO_INCREMENT PRIMARY KEY,
            user_id INT NOT NULL,
            opening_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
            opening_notes TEXT NULL,
            closed_by INT NULL,
            closing_amount DECIMAL(12,2) DEFAULT NULL,
            expected_closing_amount DECIMAL(12,2) DEFAULT NULL,
            closing_difference DECIMAL(12,2) DEFAULT NULL,
            closing_notes TEXT NULL,
            opened_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            closed_at DATETIME DEFAULT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            INDEX idx_closed_at (closed_at),
            INDEX idx_user_closed (user_id, closed_at),
            CONSTRAINT fk_cash_user FOREIGN KEY (user_id) REFERENCES users(id),
            CONSTRAINT fk_cash_closed_by FOREIGN KEY (closed_by) REFERENCES users(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS expense_requests (
            id INT AUTO_INCREMENT PRIMARY KEY,
            expense_date DATE NOT NULL,
            category VARCHAR(120) NOT NULL,
            description TEXT NULL,
            amount DECIMAL(12,2) NOT NULL DEFAULT 0,
            status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
            created_by INT NOT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            decision_by INT NULL,
            decision_at DATETIME NULL,
            decision_notes TEXT NULL,
            INDEX idx_status (status),
            INDEX idx_expense_date (expense_date),
            INDEX idx_created_by (created_by),
            INDEX idx_decision_by (decision_by)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS stock_adjustment_requests (
            id INT AUTO_INCREMENT PRIMARY KEY,
            product_id INT NOT NULL,
            requested_quantity INT NOT NULL,
            reason TEXT NOT NULL,
            record_expense TINYINT(1) NOT NULL DEFAULT 0,
            metadata TEXT NULL,
            status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
            created_by INT NOT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            decision_by INT NULL,
            decision_at DATETIME NULL,
            decision_notes TEXT NULL,
            INDEX idx_status (status),
            INDEX idx_product_status (product_id, status),
            INDEX idx_created_by (created_by),
            INDEX idx_decision_by (decision_by),
            CONSTRAINT fk_stock_request_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
    ];
}

function setup_schema_statements_relaxed(): array
{
    return [
        "SET NAMES utf8mb4",
        "SET time_zone = '+07:00'",
        "CREATE TABLE IF NOT EXISTS users (
            id INT AUTO_INCREMENT PRIMARY KEY,
            username VARCHAR(60) NOT NULL UNIQUE,
            full_name VARCHAR(120) NOT NULL,
            role ENUM('kasir','manajer','adminsuper') NOT NULL DEFAULT 'kasir',
            password_hash VARCHAR(255) NOT NULL,
            is_active TINYINT(1) NOT NULL DEFAULT 1,
            last_login_at DATETIME NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            created_by INT NULL,
            INDEX idx_role (role),
            INDEX idx_active (is_active)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS auth_tokens (
            id INT AUTO_INCREMENT PRIMARY KEY,
            selector VARCHAR(32) NOT NULL UNIQUE,
            hashed_validator VARCHAR(255) NOT NULL,
            user_id INT NOT NULL,
            expires_at DATETIME NOT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_user (user_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS categories (
            id INT AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(120) NOT NULL UNIQUE,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS suppliers (
            id INT AUTO_INCREMENT PRIMARY KEY,
            name VARCHAR(150) NOT NULL,
            contact_person VARCHAR(120) NULL,
            phone VARCHAR(40) NULL,
            email VARCHAR(120) NULL,
            address TEXT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS products (
            id INT AUTO_INCREMENT PRIMARY KEY,
            barcode VARCHAR(64) NULL,
            name VARCHAR(180) NOT NULL,
            category_id INT NULL,
            unit VARCHAR(40) NULL,
            stock_minimum INT NOT NULL DEFAULT 0,
            description TEXT NULL,
            image_path VARCHAR(255) NULL,
            points_reward INT NOT NULL DEFAULT 0,
            is_active TINYINT(1) NOT NULL DEFAULT 1,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uk_products_barcode (barcode),
            INDEX idx_products_category (category_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS product_batches (
            id INT AUTO_INCREMENT PRIMARY KEY,
            product_id INT NOT NULL,
            supplier_id INT NULL,
            source_batch_id INT NULL,
            batch_code VARCHAR(80) NOT NULL,
            stock_in INT NOT NULL DEFAULT 0,
            stock_remaining INT NOT NULL DEFAULT 0,
            purchase_price DECIMAL(12,2) NOT NULL DEFAULT 0,
            sell_price DECIMAL(12,2) NOT NULL DEFAULT 0,
            expiry_date DATE NULL,
            received_at DATETIME NULL,
            label_printed TINYINT(1) NOT NULL DEFAULT 0,
            label_printed_at DATETIME NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            INDEX idx_batches_product (product_id),
            INDEX idx_batches_supplier (supplier_id),
            INDEX idx_batches_expiry (expiry_date)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS product_conversions (
            id INT AUTO_INCREMENT PRIMARY KEY,
            parent_product_id INT NOT NULL,
            child_product_id INT NOT NULL,
            child_quantity DECIMAL(12,3) NOT NULL DEFAULT 0,
            auto_breakdown TINYINT(1) NOT NULL DEFAULT 0,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uk_conversion_child (child_product_id),
            INDEX idx_conversion_parent (parent_product_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS stock_adjustments (
            id INT AUTO_INCREMENT PRIMARY KEY,
            product_id INT NOT NULL,
            batch_id INT NOT NULL,
            adjustment_type ENUM('initial','purchase','sale','return','adjust','transfer','convert_in','convert_out','expired','in') NOT NULL DEFAULT 'adjust',
            quantity INT NOT NULL DEFAULT 0,
            reason TEXT NULL,
            created_by INT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_stock_product (product_id),
            INDEX idx_stock_batch (batch_id),
            INDEX idx_stock_type (adjustment_type)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS members (
            id INT AUTO_INCREMENT PRIMARY KEY,
            member_code VARCHAR(50) NOT NULL UNIQUE,
            name VARCHAR(150) NOT NULL,
            phone VARCHAR(40) NULL,
            email VARCHAR(120) NULL,
            address TEXT NULL,
            status ENUM('active','inactive') NOT NULL DEFAULT 'active',
            points_balance INT NOT NULL DEFAULT 0,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS sales (
            id INT AUTO_INCREMENT PRIMARY KEY,
            invoice_code VARCHAR(40) NOT NULL UNIQUE,
            member_id INT NULL,
            cashier_id INT NOT NULL,
            total_items INT NOT NULL DEFAULT 0,
            subtotal DECIMAL(12,2) NOT NULL DEFAULT 0,
            discount_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
            points_used INT NOT NULL DEFAULT 0,
            points_earned INT NOT NULL DEFAULT 0,
            grand_total DECIMAL(12,2) NOT NULL DEFAULT 0,
            payment_method ENUM('cash','debit','qris','hutang') NOT NULL DEFAULT 'cash',
            cash_paid DECIMAL(12,2) NOT NULL DEFAULT 0,
            change_returned DECIMAL(12,2) NOT NULL DEFAULT 0,
            notes TEXT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            INDEX idx_sales_created (created_at),
            INDEX idx_sales_member (member_id),
            INDEX idx_sales_cashier (cashier_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS sale_items (
            id INT AUTO_INCREMENT PRIMARY KEY,
            sale_id INT NOT NULL,
            product_id INT NOT NULL,
            batch_id INT NOT NULL,
            quantity DECIMAL(12,2) NOT NULL DEFAULT 0,
            price DECIMAL(12,2) NOT NULL DEFAULT 0,
            discount DECIMAL(12,2) NOT NULL DEFAULT 0,
            total DECIMAL(12,2) NOT NULL DEFAULT 0,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_items_sale (sale_id),
            INDEX idx_items_product (product_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS member_points (
            id INT AUTO_INCREMENT PRIMARY KEY,
            member_id INT NOT NULL,
            sale_id INT NULL,
            points_change INT NOT NULL DEFAULT 0,
            description VARCHAR(255) NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_points_member (member_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS expenses (
            id INT AUTO_INCREMENT PRIMARY KEY,
            expense_date DATE NOT NULL,
            category VARCHAR(120) NOT NULL,
            description TEXT NULL,
            amount DECIMAL(12,2) NOT NULL DEFAULT 0,
            created_by INT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            INDEX idx_expense_date (expense_date),
            INDEX idx_expense_user (created_by)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS promotions (
            id INT AUTO_INCREMENT PRIMARY KEY,
            product_id INT NULL,
            promo_name VARCHAR(160) NOT NULL,
            promo_type ENUM('item','category','global') NOT NULL DEFAULT 'item',
            discount_value DECIMAL(12,2) NOT NULL DEFAULT 0,
            start_date DATE NULL,
            end_date DATE NULL,
            min_qty INT NOT NULL DEFAULT 1,
            is_active TINYINT(1) NOT NULL DEFAULT 1,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            INDEX idx_promo_product (product_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS store_settings (
            id INT AUTO_INCREMENT PRIMARY KEY,
            store_name VARCHAR(150) NOT NULL,
            address TEXT NULL,
            phone VARCHAR(40) NULL,
            logo_path VARCHAR(255) NULL,
            notes TEXT NULL,
            updated_at DATETIME NOT NULL
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS member_debts (
            id INT AUTO_INCREMENT PRIMARY KEY,
            sale_id INT NOT NULL,
            member_id INT NOT NULL,
            principal_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
            admin_fee DECIMAL(12,2) NOT NULL DEFAULT 0,
            total_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
            paid_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
            status ENUM('open','partial','paid') NOT NULL DEFAULT 'open',
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            UNIQUE KEY uk_debt_sale (sale_id),
            INDEX idx_debt_member (member_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS member_debt_payments (
            id INT AUTO_INCREMENT PRIMARY KEY,
            debt_id INT NOT NULL,
            member_id INT NOT NULL,
            sale_id INT NOT NULL,
            amount DECIMAL(12,2) NOT NULL DEFAULT 0,
            note VARCHAR(255) NULL,
            paid_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            created_by INT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            INDEX idx_debt_payment (debt_id),
            INDEX idx_debt_member (member_id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS cash_drawer_sessions (
            id INT AUTO_INCREMENT PRIMARY KEY,
            user_id INT NOT NULL,
            opening_amount DECIMAL(12,2) NOT NULL DEFAULT 0,
            opening_notes TEXT NULL,
            closed_by INT NULL,
            closing_amount DECIMAL(12,2) DEFAULT NULL,
            expected_closing_amount DECIMAL(12,2) DEFAULT NULL,
            closing_difference DECIMAL(12,2) DEFAULT NULL,
            closing_notes TEXT NULL,
            opened_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            closed_at DATETIME DEFAULT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
            INDEX idx_closed_at (closed_at),
            INDEX idx_user_closed (user_id, closed_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS expense_requests (
            id INT AUTO_INCREMENT PRIMARY KEY,
            expense_date DATE NOT NULL,
            category VARCHAR(120) NOT NULL,
            description TEXT NULL,
            amount DECIMAL(12,2) NOT NULL DEFAULT 0,
            status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
            created_by INT NOT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            decision_by INT NULL,
            decision_at DATETIME NULL,
            decision_notes TEXT NULL,
            INDEX idx_status (status),
            INDEX idx_expense_date (expense_date),
            INDEX idx_created_by (created_by),
            INDEX idx_decision_by (decision_by)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
        "CREATE TABLE IF NOT EXISTS stock_adjustment_requests (
            id INT AUTO_INCREMENT PRIMARY KEY,
            product_id INT NOT NULL,
            requested_quantity INT NOT NULL,
            reason TEXT NOT NULL,
            record_expense TINYINT(1) NOT NULL DEFAULT 0,
            metadata TEXT NULL,
            status ENUM('pending','approved','rejected') NOT NULL DEFAULT 'pending',
            created_by INT NOT NULL,
            created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
            decision_by INT NULL,
            decision_at DATETIME NULL,
            decision_notes TEXT NULL,
            INDEX idx_status (status),
            INDEX idx_product_status (product_id, status),
            INDEX idx_created_by (created_by),
            INDEX idx_decision_by (decision_by)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
    ];
}
